# Generated by Django 6.0.5 on 2026-05-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('flight', 'seat_number')},
        ),
    ]
